### PR TITLE
Using stable UIDs for tags on outscale resources

### LINKED ISSUE #261: [Bug]: Cluster UID is used in all resource names
### What happened

After [pivoting](https://cluster-api.sigs.k8s.io/clusterctl/commands/move.html), the `Cluster` resource has a new UID and the controllers can't find the actual resources that have the old cluster UID in their tags anymore.

### Step to reproduce

* Create a management cluster
* Create a workload cluster
* Pivot

### Expected to happen

The controllers are able to find the resources after pivoting.

### Add anything

It probably would cause the same problem if the cluster is backed up and restored using a tool like Velero.

### cluster-api output

```http
POST /api/v1/ReadVms HTTP/1.1
Host: api.eu-west-2.outscale.com
User-Agent: cluster-api-provider-outscale/DEV
Content-Length: 108
Accept: application/json
Authorization: redacted, SignedHeaders=accept;content-type;host;x-amz-date, Signature=15e4fc61e8919f4f3c2371d541c53ac0867dca919b8c3c352e93fed6a11a16f4
Content-Type: application/json
X-Amz-Date: 20230823T123348Z
Accept-Encoding: gzip

 

{"Filters":{"TagKeys":["OscK8sClusterID/kapi-20d96cd1-9f08-4b68-ac2b-3273e408b8d5"],"TagValues":["owned"]}}

 

HTTP/1.1 200 OK
Content-Length: 81
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json
Date: Wed, 23 Aug 2023 12:33:48 GMT
Referrer-Policy: same-origin
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubdomains;
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

 

{"Vms":[],"ResponseContext":{"RequestId":"701a78e2-d3a2-4ba5-a65a-b2c86c91ef3d"}}
{"level":"error","ts":"2023-08-23T12:33:48Z","msg":"Reconciler error","controller":"oscmachinetemplate","controllerGroup":"infrastructure.cluster.x-k8s.io","controllerKind":"OscMachineTemplate","OscMachineTemplate":{"name":"kapi-control-plane","namespace":"capi-cluster"},"namespace":"capi-cluster","name":"kapi-control-plane","reconcileID":"ef53d6b0-5922-4881-9a43-c3db76f5e7bb","error":"failed to find server type for tinav5.c4r16p1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
```

### Environment

```markdown
- Kubernetes version: (use `kubectl version`): v1.27.4
- OS (e.g. from `/etc/os-release`): Talos v1.4.8
- Kernel (e.g. `uname -a`):
- cluster-api-provider-outscale version: v0.2.2
- cluster-api version: v1.5.0
- Install tools: local kind cluster
- Kubernetes Distribution: Talos
- Kubernetes Diestribution version: v1.4.8
```

### PR DESCRIPTION
**Pull request by azert9**
**What type of PR is this?**

/kind bug               Fixes a newly discovered bug.

**What this PR does / why we need it**:

This  provider sets `OscK8sClusterID/{{CLUSTER ID}}` tags on all created Outscale resources. The problem is that the cluster id depends on a kubernetes resource UID, which changes during [pivot operations](https://cluster-api.sigs.k8s.io/clusterctl/commands/move.html).

**Which issue(s) this PR fixes** :

Fixes #261

**Special notes for your reviewer**:

I can think of two ways to address this issue:
* Not using an UID in tags (only the cluster name).
* Storing the UID in a label to make it stable across migrations.

This PR explores the second solution.

**TODOs**:

- [ ] validate this is the correct approach
- [ ] find a suitable name for the label
- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

### CODE REVIEW

**Comment by outscale-vbr** [comment]
Hi @azert9 please rebase on main branch.
And your PR will be tested on (https://github.com/outscale/cluster-api-provider-outscale/pull/265) because we deactivate secret from fork.

**Comment by azert9** [comment]
Hi, just rebased. I did not have time to test end to end yet though.

**Comment by outscale-vbr** [comment]
@azert9 
Our Ci doesn't detect regression (https://github.com/outscale/cluster-api-provider-outscale/pull/266) and i also test iwith my cluster.

**Comment by azert9** [comment]
It seems to be ok on my side as well :)

**Comment by outscale-vbr** [comment]
Ok good
A new release will be available very soon :)

**Review by outscale-vbr — APPROVED** [review]
OK

**Comment by outscale-vbr** [comment]
The new release v0.2.3 are now available :)

**Pull request merged**
